[theme]
base = "light"
primaryColor = "#8B4229"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F3EE"
textColor = "#213B3F"
font = "sans serif"

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
